# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embracoprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supplierprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmbracoProfile',
        ),
        migrations.DeleteModel(
            name='SupplierProfile',
        ),
    ]
