# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estufa', '0002_auto_20170704_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Padrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Irrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Luminosidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='Log_Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now=True)),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.Estufa')),
            ],
        ),
    ]
