# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Padrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estufa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Irrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Luminosidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now=True)),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.Estufa')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('planta', models.CharField(default='', max_length=50)),
                ('estufa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.Estufa')),
            ],
        ),
        migrations.AddField(
            model_name='log_luminosidade',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.Slot'),
        ),
        migrations.AddField(
            model_name='log_irrigacao',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estufa.Slot'),
        ),
    ]
